### ISSUE TITLE
Move Twitter API credentials to config file

### ISSUE THREAD

**Issue by lex111** [mathieuhendey/final-year-project#33]
Now they are kept in the [public source code](https://github.com/mathieuhendey/final-year-project/blob/master/api/twitteranalyser/twitteranalyser/constants.py#L5-L8), which is a bad practice.
Should move to a env-based config file (for Python, you can use [it](https://github.com/theskumar/python-dotenv)).

**Comment by mathieuhendey** [comment]
Thanks for bringing this to my attention, I'll fix it ASAP, only just noticed this issue had been opened!
